# Generated by Django 4.0.3 on 2022-09-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=200)),
            ],
        ),
    ]
